// Pinnacle data — products, posts, testimonials
window.PINNACLE_DATA = {
  exchangeRate: 1500, // 1 USD = 1500 NGN

  collections: [
    { id: 'all', label: 'All' },
    { id: 'fragrance', label: 'Fragrance' },
    { id: 'bodycare', label: 'Body Care' },
    { id: 'skincare', label: 'Skincare' },
    { id: 'supplements', label: 'Supplements' },
    { id: 'coaching', label: 'Coaching' },
    { id: 'bestsellers', label: 'Bestsellers' },
  ],

  products: [
    {
      id: 'glow-collagen',
      name: 'Radiant Glow Collagen+',
      tagline: 'Marine collagen with biotin & vitamin C',
      collection: 'supplements',
      collections: ['supplements', 'bestsellers'],
      priceUSD: 48,
      compareUSD: 60,
      rating: 4.9,
      reviews: 412,
      badge: 'Bestseller',
      shortDesc: 'A daily dose of marine collagen peptides, biotin and Vitamin C — clinically formulated to restore skin elasticity, strengthen hair, and support nail growth from within.',
      benefits: [
        'Visibly firmer, more elastic skin in 6 weeks',
        'Stronger hair follicles & reduced shedding',
        'Joint comfort & mobility',
        'Sugar-free, no artificial colors',
      ],
      ingredients: 'Hydrolyzed Marine Collagen (Type I), Biotin, Vitamin C, Hyaluronic Acid, Zinc, Bamboo Silica.',
      directions: 'Mix one scoop (10g) into water, smoothie or coffee, once daily. Consistency matters — give it 6–8 weeks.',
      image: 'assets/colagen.webp',
      hue: 'rose',
    },
    {
      id: 'calm-magnesium',
      name: 'Deep Calm Magnesium',
      tagline: 'Triple-magnesium complex for sleep & stress',
      collection: 'supplements',
      collections: ['supplements', 'bestsellers'],
      priceUSD: 32,
      rating: 4.8,
      reviews: 287,
      badge: 'New',
      shortDesc: 'A bioavailable blend of magnesium glycinate, malate, and citrate to quiet the nervous system, deepen sleep, and ease tension headaches.',
      benefits: [
        'Falls asleep faster, stays asleep longer',
        'Relaxed muscles, fewer cramps',
        'Calmer mood under pressure',
        'Non-habit forming',
      ],
      ingredients: 'Magnesium Glycinate, Magnesium Malate, Magnesium Citrate, L-Theanine, Vitamin B6.',
      directions: 'Two capsules 30 minutes before bed with water.',
      hue: 'lavender',
    },
    {
      id: 'gut-reset',
      name: 'Gut Reset Probiotic',
      tagline: '40 billion CFU, 12 strains',
      collection: 'supplements',
      collections: ['supplements'],
      priceUSD: 39,
      rating: 4.7,
      reviews: 198,
      shortDesc: 'A clinically-studied multi-strain probiotic with prebiotic fiber to rebuild a balanced gut, ease bloating, and restore digestive comfort.',
      benefits: [
        'Reduces bloating in 14 days',
        'Restores microbiome diversity',
        'Supports immune resilience',
        'Shelf-stable, no refrigeration',
      ],
      ingredients: '12 probiotic strains (40 billion CFU), Inulin prebiotic, Saccharomyces boulardii.',
      directions: 'One capsule daily, with or without food.',
      hue: 'sage',
    },
    {
      id: 'velvet-serum',
      name: 'Velvet Glow Vitamin C Serum',
      tagline: '15% L-ascorbic acid + ferulic acid',
      collection: 'skincare',
      collections: ['skincare', 'bestsellers'],
      priceUSD: 54,
      compareUSD: 68,
      rating: 4.9,
      reviews: 521,
      badge: 'Bestseller',
      shortDesc: 'A potent, photo-stable Vitamin C serum that brightens uneven tone, fades dark spots, and shields skin from environmental damage.',
      benefits: [
        'Fades hyperpigmentation in 8 weeks',
        'Visibly brighter, even-toned skin',
        'Antioxidant shield against pollution',
        'Lightweight, fast-absorbing',
      ],
      ingredients: '15% L-Ascorbic Acid, Ferulic Acid, Vitamin E, Hyaluronic Acid, Niacinamide.',
      directions: 'AM: 4–5 drops on clean skin before moisturizer & SPF.',
      image: 'assets/vit.webp',
      hue: 'amber',
    },
    {
      id: 'silk-cream',
      name: 'Silk Repair Night Cream',
      tagline: 'Bakuchiol + peptide complex',
      collection: 'skincare',
      collections: ['skincare'],
      priceUSD: 62,
      rating: 4.8,
      reviews: 234,
      shortDesc: 'A whipped, deeply nourishing night cream with retinol-alternative bakuchiol and a 5-peptide complex to firm, smooth, and replenish overnight.',
      benefits: [
        'Visibly firmer skin in 4 weeks',
        'Smooths fine lines',
        'Deeply hydrating, never greasy',
        'Pregnancy-safe',
      ],
      ingredients: 'Bakuchiol, 5-Peptide Complex, Squalane, Ceramides, Shea Butter.',
      directions: 'PM: massage a pearl-sized amount into clean skin.',
      hue: 'cream',
    },
    {
      id: 'gentle-cleanser',
      name: 'Gentle Renewal Cleanser',
      tagline: 'pH-balanced cream cleanser',
      collection: 'skincare',
      collections: ['skincare'],
      priceUSD: 28,
      rating: 4.7,
      reviews: 167,
      shortDesc: 'A creamy, pH-balanced cleanser that lifts away makeup and impurities without stripping — leaving skin soft, calm, and never tight.',
      benefits: [
        'Removes makeup & SPF cleanly',
        'Soothes sensitive, reactive skin',
        'No tight, squeaky feeling',
        'Fragrance-free',
      ],
      ingredients: 'Glycerin, Oat Extract, Centella Asiatica, Panthenol, Sodium PCA.',
      directions: 'AM & PM: massage into damp skin, rinse with lukewarm water.',
      hue: 'sage',
    },
    {
      id: 'wellness-1on1',
      name: 'Wellness 1:1 with Mercy',
      tagline: '60-minute personal consultation',
      collection: 'coaching',
      collections: ['coaching'],
      priceUSD: 180,
      rating: 5.0,
      reviews: 89,
      badge: 'Limited',
      shortDesc: 'A private 60-minute virtual session with Mercy Ikpe to map out your personal wellness path — covering nutrition, sleep, skin, stress and supplement strategy.',
      benefits: [
        'Personalized wellness blueprint',
        '60 minutes 1:1 over Zoom',
        'Follow-up notes & 30-day plan',
        '20% off your next product order',
      ],
      ingredients: 'Held over Zoom. Bookings within 14 days. Rescheduling welcomed with 24h notice.',
      directions: 'Book a slot, complete a short intake form, then we meet.',
      hue: 'gold',
    },
    {
      id: 'premium-circle',
      name: 'The Pinnacle Circle — Premium',
      tagline: 'Monthly membership',
      collection: 'coaching',
      collections: ['coaching', 'bestsellers'],
      priceUSD: 29,
      rating: 4.9,
      reviews: 312,
      badge: 'Members favorite',
      shortDesc: 'A monthly membership for women serious about their wellness journey — exclusive content, live group calls, member-only product drops, and priority access to Mercy.',
      benefits: [
        'Live monthly group call with Mercy',
        '15% off all products, always',
        'Members-only product drops',
        'Private community & weekly rituals',
      ],
      ingredients: 'Cancel anytime. First-month satisfaction guarantee.',
      directions: 'Sign up, get welcome kit instantly, join the next live call.',
      hue: 'plum',
    },

    /* === Pinnacle Signature collection === */
    {
      id: 'midnight-bloom',
      name: 'Midnight Bloom Eau de Parfum',
      tagline: 'A signature scent for evenings that matter',
      collection: 'fragrance',
      collections: ['fragrance', 'bestsellers'],
      brand: 'Pinnacle Signature',
      priceUSD: 38, priceNGN: 57000,
      rating: 4.8, reviews: 246,
      badge: 'Bestseller',
      shortDesc: 'A deep, velvety fragrance built around warm florals and a sensual amber base — designed to linger softly long after the room has emptied.',
      benefits: ['Long-lasting evening wear', 'Warm floral-amber profile', 'Refillable glass flacon', 'Cruelty-free formulation'],
      ingredients: 'Top: pink pepper, bergamot. Heart: rose, iris. Base: amber, cashmere wood, vanilla.',
      directions: 'Spray onto pulse points — wrists, neck, décolletage.',
      hue: 'plum',
    },
    {
      id: 'first-light',
      name: 'First Light Eau de Toilette',
      tagline: 'Bright. Clean. Effortless.',
      collection: 'fragrance',
      collections: ['fragrance'],
      brand: 'Pinnacle Signature',
      priceUSD: 26, priceNGN: 39000,
      rating: 4.7, reviews: 184,
      badge: 'New',
      shortDesc: 'A weightless aromatic fragrance — citrus and herbs at the top, soft woods at the base. Made for daylight, made to wear often.',
      benefits: ['Fresh aromatic-woody character', 'Versatile day-to-night wear', 'Lightweight, never overpowering', 'Cruelty-free'],
      ingredients: 'Top: mint, cardamom, lemon. Heart: lavender, geranium. Base: vetiver, light woods.',
      directions: 'Apply to pulse points after showering. Reapply mid-day if you like.',
      hue: 'lavender',
    },
    {
      id: 'silk-bloom-deo',
      name: 'Silk Bloom Roll-On',
      tagline: 'Gentle 24-hour protection',
      collection: 'bodycare',
      collections: ['bodycare', 'bestsellers'],
      brand: 'Pinnacle Daily',
      priceUSD: 8, priceNGN: 12000,
      rating: 4.7, reviews: 312,
      badge: 'Bestseller',
      shortDesc: 'A soft floral roll-on that glides on smoothly, dries quickly, and gives you 24 hours of clean, confident protection.',
      benefits: ['24-hour sweat & odour protection', 'Soft floral signature', 'Glides on smoothly', 'No white marks or stickiness'],
      ingredients: 'Active anti-perspirant complex, glycerin, vitamin E, fragrance.',
      directions: 'Apply to clean, dry underarms each morning. Allow to dry before dressing.',
      hue: 'rose',
    },
    {
      id: 'cool-cedar-deo',
      name: 'Cool Cedar Roll-On',
      tagline: 'Crisp. Clean. All-day.',
      collection: 'bodycare',
      collections: ['bodycare'],
      brand: 'Pinnacle Daily',
      priceUSD: 8, priceNGN: 12000,
      rating: 4.6, reviews: 198,
      shortDesc: 'A men’s roll-on with a clean cedar-and-mint signature. Fast-drying, gentle on shaved skin, and reliable for the long day.',
      benefits: ['24-hour anti-perspirant action', 'Cool cedar-mint scent', 'Non-sticky, fast-drying', 'Gentle on shaved skin'],
      ingredients: 'Active anti-perspirant complex, glycerin, allantoin, fragrance.',
      directions: 'Roll onto clean, dry underarms each morning.',
      hue: 'lavender',
    },
    {
      id: 'amber-veil-deo',
      name: 'Amber Veil Roll-On',
      tagline: 'Powdery, warm, sensual',
      collection: 'bodycare',
      collections: ['bodycare'],
      brand: 'Pinnacle Daily',
      priceUSD: 8, priceNGN: 12000,
      rating: 4.6, reviews: 142,
      shortDesc: 'A warm, powdery roll-on inspired by our Midnight Bloom signature — it carries the scent into your everyday ritual.',
      benefits: ['24-hour protection', 'Warm powdery dry-down', 'Smooth glide application', 'Travel-friendly format'],
      ingredients: 'Active anti-perspirant complex, glycerin, vitamin E, fragrance.',
      directions: 'Apply each morning to clean, dry underarms.',
      hue: 'cream',
    },
    {
      id: 'oak-grove-deo',
      name: 'Oak Grove Roll-On',
      tagline: 'A grown-up woody finish',
      collection: 'bodycare',
      collections: ['bodycare'],
      brand: 'Pinnacle Daily',
      priceUSD: 8, priceNGN: 12000,
      rating: 4.6, reviews: 121,
      shortDesc: 'A sophisticated woody-aromatic anti-perspirant that quietly finishes a polished morning ritual.',
      benefits: ['24-hour anti-perspirant', 'Sophisticated woody scent', 'Quick-drying formula', 'Non-irritating on shaved skin'],
      ingredients: 'Active anti-perspirant complex, glycerin, allantoin, fragrance.',
      directions: 'Roll onto clean, dry underarms each morning.',
      hue: 'amber',
    },
    {
      id: 'soft-glow-deo',
      name: 'Soft Glow Roll-On',
      tagline: 'Light, luminous, feminine',
      collection: 'bodycare',
      collections: ['bodycare', 'bestsellers'],
      brand: 'Pinnacle Daily',
      priceUSD: 8, priceNGN: 12000,
      rating: 4.7, reviews: 268,
      badge: 'Bestseller',
      shortDesc: 'A luminous floral roll-on with a gentle, powdery dry-down — day-long freshness without anything heavy.',
      benefits: ['24-hour fresh protection', 'Soft floral signature', 'Powdery dry-down', 'Travel-friendly'],
      ingredients: 'Active anti-perspirant complex, glycerin, vitamin E, fragrance.',
      directions: 'Apply each morning to clean, dry underarms.',
      hue: 'rose',
    },
    {
      id: 'event-ready-set',
      name: 'Event-Ready Skincare Set',
      tagline: 'Glow-ready in three steps',
      collection: 'skincare',
      collections: ['skincare', 'bestsellers'],
      brand: 'Pinnacle Skincare',
      priceUSD: 78, priceNGN: 117000,
      rating: 4.8, reviews: 56,
      badge: 'Set',
      shortDesc: 'A three-step pre-event ritual — brightening cleanser, hydrating serum, and luminous day cream. Skin that looks lit-from-within in time for any occasion.',
      benefits: ['Visibly brightens & evens tone', '3-step ritual, salon-finish at home', 'Lightweight, fast-absorbing', 'Suitable for all skin types'],
      ingredients: 'Cleanser, Hydrating Serum, Day Cream. Niacinamide, Vitamin C derivative, Hyaluronic Acid.',
      directions: '1. Cleanse · 2. Apply serum · 3. Finish with day cream. AM & PM.',
      hue: 'amber',
    },
  ],

  testimonials: [
    {
      name: 'Adaeze O.',
      location: 'Lagos, Nigeria',
      role: 'Premium Member, 2 years',
      quote: 'I came for the collagen. I stayed for the community. Mercy has built something rare here — wellness that actually fits a Nigerian woman\'s life.',
    },
    {
      name: 'Funmi A.',
      location: 'Abuja, Nigeria',
      role: 'Customer since 2023',
      quote: 'The Magnesium changed my sleep. The Vitamin C serum changed my skin. The 1:1 with Mercy changed my whole approach to my body.',
    },
    {
      name: 'Sandra E.',
      location: 'London, UK',
      role: 'Premium Member',
      quote: 'I have tried every supplement brand. Pinnacle is the only one I have stayed loyal to — because the products work and Mercy answers personally.',
    },
  ],

  posts: [
    {
      id: 'morning-ritual',
      category: 'Lifestyle',
      title: 'The 12-minute morning ritual that quietly changes everything',
      excerpt: 'You don\'t need an hour. You need twelve minutes, done with intention. Here is the order, the science, and the mistake most women make.',
      readTime: '6 min',
      date: 'Apr 22, 2026',
      image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=900&q=80',
      hue: 'rose',
    },
    {
      id: 'collagen-truth',
      category: 'Wellness',
      title: 'What the collagen industry isn\'t telling you',
      excerpt: 'Type I, Type II, marine, bovine, peptides vs. powder — what actually works after 35, what doesn\'t, and what to look for on a label.',
      readTime: '9 min',
      date: 'Apr 15, 2026',
      image: 'https://images.unsplash.com/photo-1559057269-0f2bafcb7a26?auto=format&fit=crop&w=900&q=80',
      hue: 'amber',
    },
    {
      id: 'stress-skin',
      category: 'Skin',
      title: 'Your skin is keeping score: stress, cortisol, and the breakout cycle',
      excerpt: 'Why the breakout you blamed on chocolate is actually about your nervous system — and the four habits that calm both.',
      readTime: '7 min',
      date: 'Apr 8, 2026',
      image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=900&q=80',
      hue: 'sage',
    },
  ],
};
